# fly.toml app configuration file generated for rompus-room-site-primo on 2023-12-13T16:41:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rompus-room-site-primo"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 500
    hard_limit = 550

  [http_service.http_options]
    [http_service.http_options.headers]
      Access-Control-Allow-Credentials = "true"
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET,OPTIONS,PATCH,DELETE,POST,PUT"
      Access-Control-Allow-Headers = "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
